from __future__ import annotations

from typing import TYPE_CHECKING

from ipsw_diff_catalog.model import CatalogError, MigrationSpec

if TYPE_CHECKING:
    from collections.abc import Callable
    from pathlib import Path


def load_archive_specs(specs_dir: Path, destination_repository: str) -> tuple[MigrationSpec, ...]:
    paths = sorted(specs_dir.glob("*.json"))
    if not paths:
        raise CatalogError(f"no migration specs found in {specs_dir}")
    loaded: list[MigrationSpec] = []
    for path in paths:
        spec = MigrationSpec.from_path(path)
        if path.stem != spec.identifier:
            raise CatalogError(
                f"migration spec filename must match id: {path.name} != {spec.identifier}.json"
            )
        if spec.destination.repository == destination_repository:
            loaded.append(spec)
    if not loaded:
        raise CatalogError(
            f"no migration specs route to destination repository {destination_repository}"
        )
    return _validated_archive_specs(tuple(loaded))


def _validated_archive_specs(
    specifications: tuple[MigrationSpec, ...],
) -> tuple[MigrationSpec, ...]:
    if not specifications:
        raise CatalogError("archive specs must not be empty")
    _require_shared_value(
        specifications,
        "platform",
        lambda spec: spec.platform,
    )
    _require_shared_value(
        specifications,
        "major version",
        lambda spec: str(spec.major_version),
    )
    _require_shared_value(
        specifications,
        "source repository",
        lambda spec: spec.source.repository,
    )
    _require_shared_value(
        specifications,
        "destination repository",
        lambda spec: spec.destination.repository,
    )
    _require_unique(specifications, "id", lambda spec: spec.identifier)
    _require_unique(specifications, "source path", lambda spec: spec.source.path)
    _require_unique(
        specifications,
        "destination payload path",
        lambda spec: spec.destination.payload_path,
    )
    _require_unique(
        specifications,
        "destination manifest path",
        lambda spec: spec.destination.manifest_path,
    )
    return tuple(
        sorted(
            specifications,
            key=lambda spec: (
                spec.device,
                spec.source.path,
            ),
        )
    )


def _require_shared_value(
    specifications: tuple[MigrationSpec, ...],
    label: str,
    key: Callable[[MigrationSpec], str],
) -> None:
    values = {key(spec) for spec in specifications}
    if len(values) != 1:
        raise CatalogError(f"archive specs must share one {label}: {sorted(values)}")


def _require_unique(
    specifications: tuple[MigrationSpec, ...],
    label: str,
    key: Callable[[MigrationSpec], str],
) -> None:
    seen: set[str] = set()
    for spec in specifications:
        value = key(spec)
        if value in seen:
            raise CatalogError(f"duplicate archive spec {label}: {value}")
        seen.add(value)


def archive_readme(specifications: tuple[MigrationSpec, ...]) -> str:
    specifications = _validated_archive_specs(specifications)
    platform = specifications[0].platform
    major_version = specifications[0].major_version
    source_repository = specifications[0].source.repository
    lines = [
        f"# {platform} {major_version} firmware diffs",
        "",
        f"Browsable historical firmware-diff payloads for {platform} {major_version},",
        "migrated from",
        f"[the source corpus]({source_repository}).",
        "",
        "This is an archive shard. It does not discover releases, download firmware,",
        "generate new diffs, or advance a mutable baseline.",
        "",
        "<!-- Generated by `ipsw-diff-catalog render-archive`; do not edit manually. -->",
        "",
        "## Available diffs",
        "",
        "Rows are grouped by device and sorted by immutable source path; no linear",
        "release sequence is implied.",
        "",
        "| Device | Comparison | Manifest |",
        "| --- | --- | --- |",
    ]
    for spec in specifications:
        comparison = (
            f"[{spec.previous.version} ({spec.previous.build}) → "
            f"{spec.next.version} ({spec.next.build})]({spec.entrypoint})"
        )
        manifest = f"[provenance]({spec.destination.manifest_path})"
        lines.append(f"| `{spec.device}` | {comparison} | {manifest} |")
    lines.extend(
        [
            "",
            "## Layout and integrity",
            "",
            "- `diffs/` contains the browsable Markdown payloads.",
            "- `manifests/` contains machine-readable source provenance and tree identity.",
            "- The central catalog links only to immutable shard commits after",
            "  source-to-destination verification.",
            "",
        ]
    )
    return "\n".join(lines)


def render_archive(
    specs_dir: Path,
    destination_repository: str,
    output: Path,
    *,
    check: bool,
) -> int:
    specifications = load_archive_specs(specs_dir, destination_repository)
    content = archive_readme(specifications)
    if check:
        try:
            observed = output.read_text(encoding="utf-8")
        except OSError as error:
            raise CatalogError(f"cannot read archive README {output}: {error}") from error
        if observed != content:
            raise CatalogError(f"generated archive README is stale: {output}")
    else:
        try:
            output.write_text(content, encoding="utf-8")
        except OSError as error:
            raise CatalogError(f"cannot write archive README {output}: {error}") from error
    return len(specifications)
