from __future__ import annotations

import re
from typing import TYPE_CHECKING

from ipsw_diff_catalog.model import (
    CatalogEntry,
    CatalogError,
    JsonObject,
    canonical_json,
    read_json_object,
)

if TYPE_CHECKING:
    from collections.abc import Callable, Iterable
    from pathlib import Path

_APPLE_BUILD = re.compile(r"(\d+)([A-Z])(\d+)([A-Za-z]*)")
_APPLE_BETA_BUILD_FLOOR = 1000
_LATEST_PER_PLATFORM = 5
_TABLE_HEADER = (
    "| Device | Comparison | Integrity |",
    "| --- | --- | --- |",
)


def load_entries(entries_dir: Path) -> tuple[CatalogEntry, ...]:
    paths = sorted(entries_dir.glob("*.json"))
    if not paths:
        raise CatalogError(f"no catalog entries found in {entries_dir}")
    loaded: list[CatalogEntry] = []
    for path in paths:
        entry = CatalogEntry.from_object(read_json_object(path))
        if path.stem != entry.identifier:
            raise CatalogError(
                f"catalog entry filename must match id: {path.name} != {entry.identifier}.json"
            )
        loaded.append(entry)
    entries = tuple(loaded)
    _require_unique(entries, "id", lambda entry: entry.identifier)
    _require_unique(
        entries,
        "destination repository/path",
        lambda entry: f"{entry.destination_repository}:{entry.payload_path}",
    )
    _require_unique(
        entries,
        "source commit/path",
        lambda entry: f"{entry.source.commit}:{entry.source.path}",
    )
    return tuple(
        sorted(
            entries,
            key=lambda entry: (
                entry.platform.casefold(),
                -entry.major_version,
                entry.next.version,
                entry.next.build,
                entry.previous.version,
                entry.previous.build,
                entry.identifier,
            ),
        )
    )


def _require_unique(
    entries: Iterable[CatalogEntry],
    label: str,
    key: Callable[[CatalogEntry], str],
) -> None:
    seen: set[str] = set()
    for entry in entries:
        value = key(entry)
        if value in seen:
            raise CatalogError(f"duplicate catalog {label}: {value}")
        seen.add(value)


def catalog_object(entries: tuple[CatalogEntry, ...]) -> JsonObject:
    return {"schema_version": 1, "entries": [entry.data for entry in entries]}


def _version_key(version: str) -> tuple[int, ...]:
    numeric = version.split(" ", maxsplit=1)[0]
    return tuple(int(part) for part in numeric.split("."))


def _build_key(build: str) -> tuple[int, str, int, int, str]:
    match = _APPLE_BUILD.fullmatch(build)
    if match is None:
        return (0, "", 0, 0, build)
    os_version, train, number, suffix = match.groups()
    numeric = int(number)
    release_rank = 0 if numeric >= _APPLE_BETA_BUILD_FLOOR else 1
    return (int(os_version), train, release_rank, numeric, suffix)


def _release_key(entry: CatalogEntry) -> tuple[object, ...]:
    return (
        _version_key(entry.next.version),
        _build_key(entry.next.build),
        _version_key(entry.previous.version),
        _build_key(entry.previous.build),
        entry.identifier,
    )


def _append_table(lines: list[str], entries: list[CatalogEntry]) -> None:
    lines.extend(_TABLE_HEADER)
    for entry in sorted(entries, key=_release_key, reverse=True):
        manifest = (
            f"[manifest]({entry.destination_repository}/blob/"
            f"{entry.destination_commit}/{entry.manifest_path})"
        )
        integrity = (
            f"`{entry.inventory.tree[:12]}` · {entry.inventory.file_count:,} files · "
            f"{entry.inventory.logical_bytes:,} bytes · {manifest}"
        )
        lines.append(f"| `{entry.device}` | {_comparison_link(entry)} | {integrity} |")


def _comparison_link(entry: CatalogEntry) -> str:
    return (
        f"[{entry.previous.version} ({entry.previous.build}) → "
        f"{entry.next.version} ({entry.next.build})]"
        f"({entry.destination_repository}/blob/"
        f"{entry.destination_commit}/{entry.entrypoint})"
    )


def _latest_cell(entries: list[CatalogEntry]) -> str:
    if not entries:
        return "—"
    newest = sorted(entries, key=_release_key, reverse=True)[:_LATEST_PER_PLATFORM]
    return "<br>".join(_comparison_link(entry) for entry in newest)


def render_readme(entries: tuple[CatalogEntry, ...]) -> str:
    lines = [
        "# ipsw-diff catalog",
        "",
        "A small, machine-verified index of browsable Apple firmware-diff shards.",
        "The legacy corpus remains authoritative until each diff passes the same",
        "source-to-default-branch verification recorded here.",
        "",
        "<!-- Generated by `ipsw-diff-catalog render`; do not edit the indexes manually. -->",
        "",
        "## Latest diffs",
        "",
        "Up to five newest diffs per platform are side by side and sorted newest-first.",
        "Full integrity details are folded into the version browser below.",
    ]

    grouped: dict[tuple[str, int], list[CatalogEntry]] = {}
    for entry in entries:
        grouped.setdefault((entry.platform, entry.major_version), []).append(entry)

    platforms = ["iOS", "macOS"]
    latest_major: dict[str, int | None] = {}
    latest_entries: dict[str, list[CatalogEntry]] = {}
    for platform in platforms:
        majors = [major for candidate, major in grouped if candidate == platform]
        major = max(majors) if majors else None
        latest_major[platform] = major
        latest_entries[platform] = grouped[(platform, major)] if major is not None else []
    ios_label = f"iOS {latest_major['iOS']}" if latest_major["iOS"] is not None else "iOS"
    macos_label = f"macOS {latest_major['macOS']}" if latest_major["macOS"] is not None else "macOS"
    lines.extend(
        [
            "",
            f"| {ios_label} | {macos_label} |",
            "| --- | --- |",
            f"| {_latest_cell(latest_entries['iOS'])} | {_latest_cell(latest_entries['macOS'])} |",
            "",
            "## Browse all diffs",
            "",
        ]
    )
    for platform in platforms:
        platform_groups = sorted(
            (
                (major, group_entries)
                for (candidate, major), group_entries in grouped.items()
                if candidate == platform
            ),
            key=lambda group: group[0],
            reverse=True,
        )
        if not platform_groups:
            continue
        platform_count = sum(len(group_entries) for _, group_entries in platform_groups)
        platform_label = "diff" if platform_count == 1 else "diffs"
        platform_total = f"{platform_count} {platform_label}"
        lines.extend(
            [
                "<details>",
                f"<summary><strong>{platform}</strong> · {platform_total}</summary>",
                "",
            ]
        )
        for major, group_entries in platform_groups:
            diff_label = "diff" if len(group_entries) == 1 else "diffs"
            group_name = f"{platform} {major}"
            diff_count = f"{len(group_entries)} {diff_label}"
            summary = f"<summary><strong>{group_name}</strong> · {diff_count}</summary>"
            lines.extend(["<details>", summary, ""])
            _append_table(lines, group_entries)
            lines.extend(["", "</details>", ""])
        lines.extend(["</details>", ""])
    lines.extend(
        [
            "## Integrity model",
            "",
            "Every entry is created only after a fresh destination commit matches its frozen",
            "source subtree's Git tree ID, file count, logical byte total, modes, README",
            "metadata, and generated manifest. Catalog links are pinned to immutable commits.",
            "",
            "The catalog tool never selects a diff, infers platform semantics from a path,",
            "pushes, merges, deletes legacy data, or rewrites a verified payload.",
            "",
            "## Frozen migration census",
            "",
            "`census` inventories the legacy repository from one full commit, not its",
            "worktree. The reviewed [source layout policy](migration/source-layout.json)",
            "names every payload root and every intentional exclusion. The command rejects",
            "missing or overlapping policy paths and any tracked file classified zero or",
            "multiple times, then records Git object IDs, file counts, logical bytes, modes,",
            "README metadata, and explicit blocker reasons in the generated",
            "[census](migration/census.json).",
            "",
            "Both known ordinary README labels (`## Inputs` and `## IPSWs`) must satisfy the",
            "same exact title and two-IPSW contract. A census row does not select a platform,",
            "device, destination shard, or migration route; those remain reviewed spec data.",
            "",
            "`plan` combines a frozen census with an explicit reviewed policy. The policy",
            "contains the exact source-path allowlist and input-device-prefix routes. The",
            "command fails closed unless the complete ordinary destination-major set equals",
            "that allowlist, both IPSW inputs name the same device, and each row matches",
            "exactly one route. It writes deterministic specs and never copies, commits,",
            "pushes, or deletes payloads. The reviewed plan remains below `migration/` for",
            "deterministic planner checks; after destination verification, published copies",
            "move to `specs/` beside their matching catalog entries.",
            "",
            "`render-archive` selects one exact destination repository from reviewed specs",
            "and writes or checks its deterministic shard README. Rows are grouped by device",
            "and source path without claiming that branched historical data is one release",
            "sequence. It does not inspect a directory name to infer a route.",
            "",
            "## Mechanical staging",
            "",
            "`stage` requires one reviewed spec, both local repository roots, and the full",
            "destination `HEAD` commit. It refuses dirty or pre-existing targets, reconstructs",
            "the source tree twice, and leaves only the payload and manifest staged for review.",
            "Run `validate-staged` again after inspection. Neither command commits or pushes.",
            "",
            "`stage-batch` accepts two or more explicit specs that share one frozen source",
            "commit and destination shard. It verifies every member from one staged Git tree",
            "and rolls back all copier-owned batch paths if any member fails. Run",
            "`validate-staged-batch` after inspection; neither command selects or routes rows.",
            "Rollback covers handled in-process failures, not abrupt process or host termination.",
            "",
            "## Read-only discovery",
            "",
            "`discover` reads one explicitly supported iOS 27 or macOS 27 track policy,",
            "proves its baseline is the terminal merged manifest build, queries AppleDB with",
            "the exact policy selector, and emits canonical `current` or `candidate` JSON.",
            "It does not download firmware, modify a repository, schedule work, generate a",
            "diff, or publish anything.",
            "",
            "## Curated release metadata",
            "",
            "`release-metadata` enumerates every unique `(platform, build)` endpoint in the",
            "validated catalog, then requires one exact record below `osFiles/iOS` or",
            "`osFiles/macOS` at a caller-supplied AppleDB Git commit. It records AppleDB's",
            "human-curated display version, beta/RC flags, release date, and exact source",
            "path in [the release registry](metadata/releases.json).",
            "",
            "The importer reads immutable Git objects rather than the AppleDB worktree. It",
            "fails closed on missing or ambiguous builds, platform/build/version conflicts,",
            "invalid dates and flags, a substituted Git remote, or stale output. It does not",
            "infer beta ordinals from build numbers or change catalog payload facts.",
            "",
            "## Tooling",
            "",
            "```console",
            "uv sync --locked --all-groups",
            "uv run ipsw-diff-catalog --help",
            "uv run ipsw-diff-catalog stage --help",
            "uv run ipsw-diff-catalog validate-staged --help",
            "uv run ipsw-diff-catalog stage-batch --help",
            "uv run ipsw-diff-catalog validate-staged-batch --help",
            "uv run ipsw-diff-catalog census --help",
            "uv run ipsw-diff-catalog plan --help",
            "uv run ipsw-diff-catalog render-archive --help",
            "uv run ipsw-diff-catalog discover --help",
            "uv run ipsw-diff-catalog release-metadata --help",
            "uv run pytest",
            "uv run ruff format --check .",
            "uv run ruff check .",
            "uv run ty check src tests",
            "uv run ipsw-diff-catalog render --check",
            "uv run ipsw-diff-catalog audit",
            "uv run ipsw-diff-catalog census \\",
            "  --policy migration/source-layout.json \\",
            "  --source-repo /path/to/ipsw-diffs \\",
            "  --output migration/census.json \\",
            "  --check",
            "uv run ipsw-diff-catalog plan \\",
            "  --policy migration/major-26.json \\",
            "  --census migration/census.json \\",
            "  --output migration/specs-26 \\",
            "  --check",
            "uv run ipsw-diff-catalog release-metadata \\",
            "  --appledb-repo /path/to/appledb \\",
            "  --appledb-commit 3051f8643eaf5d6d7196fb3c01a0f9ade46f1dc7 \\",
            "  --output metadata/releases.json \\",
            "  --check",
            "```",
            "",
            "[Automation](docs/AUTOMATION.md) defines the separately gated migration,",
            "shard-generation, catalog-publication, and X-announcement transitions.",
            "",
        ]
    )
    return "\n".join(lines)


def _write_or_check(path: Path, content: str, *, check: bool) -> None:
    if check:
        try:
            observed = path.read_text(encoding="utf-8")
        except OSError as error:
            raise CatalogError(f"cannot check generated file {path}: {error}") from error
        if observed != content:
            raise CatalogError(f"generated file is stale: {path}")
        return
    path.write_text(content, encoding="utf-8")


def render(entries_dir: Path, readme: Path, catalog: Path, *, check: bool) -> None:
    entries = load_entries(entries_dir)
    _write_or_check(readme, render_readme(entries), check=check)
    _write_or_check(catalog, canonical_json(catalog_object(entries)), check=check)
