from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Callable, Iterable
    from pathlib import Path

from ipsw_diff_catalog.model import (
    CatalogEntry,
    CatalogError,
    JsonObject,
    canonical_json,
    read_json_object,
)


def load_entries(entries_dir: Path) -> tuple[CatalogEntry, ...]:
    paths = sorted(entries_dir.glob("*.json"))
    if not paths:
        raise CatalogError(f"no catalog entries found in {entries_dir}")
    loaded: list[CatalogEntry] = []
    for path in paths:
        entry = CatalogEntry.from_object(read_json_object(path))
        if path.stem != entry.identifier:
            raise CatalogError(
                f"catalog entry filename must match id: {path.name} != {entry.identifier}.json"
            )
        loaded.append(entry)
    entries = tuple(loaded)
    _require_unique(entries, "id", lambda entry: entry.identifier)
    _require_unique(
        entries,
        "destination repository/path",
        lambda entry: f"{entry.destination_repository}:{entry.payload_path}",
    )
    _require_unique(
        entries,
        "source commit/path",
        lambda entry: f"{entry.source.commit}:{entry.source.path}",
    )
    return tuple(
        sorted(
            entries,
            key=lambda entry: (
                entry.platform.casefold(),
                -entry.major_version,
                entry.next.version,
                entry.next.build,
                entry.previous.version,
                entry.previous.build,
                entry.identifier,
            ),
        )
    )


def _require_unique(
    entries: Iterable[CatalogEntry],
    label: str,
    key: Callable[[CatalogEntry], str],
) -> None:
    seen: set[str] = set()
    for entry in entries:
        value = key(entry)
        if value in seen:
            raise CatalogError(f"duplicate catalog {label}: {value}")
        seen.add(value)


def catalog_object(entries: tuple[CatalogEntry, ...]) -> JsonObject:
    return {"schema_version": 1, "entries": [entry.data for entry in entries]}


def render_readme(entries: tuple[CatalogEntry, ...]) -> str:
    lines = [
        "# ipsw-diff catalog",
        "",
        "A small, machine-verified index of browsable Apple firmware-diff shards.",
        "The legacy corpus remains authoritative until each diff passes the same",
        "source-to-default-branch verification recorded here.",
        "",
        "<!-- Generated by `ipsw-diff-catalog render`; do not edit the table manually. -->",
        "",
        "| Platform | Major | Device | Comparison | Integrity |",
        "| --- | ---: | --- | --- | --- |",
    ]
    for entry in entries:
        comparison = (
            f"[{entry.previous.version} ({entry.previous.build}) → "
            f"{entry.next.version} ({entry.next.build})]"
            f"({entry.destination_repository}/blob/{entry.destination_commit}/{entry.entrypoint})"
        )
        manifest = (
            f"[manifest]({entry.destination_repository}/blob/"
            f"{entry.destination_commit}/{entry.manifest_path})"
        )
        integrity = (
            f"`{entry.inventory.tree[:12]}` · {entry.inventory.file_count:,} files · "
            f"{entry.inventory.logical_bytes:,} bytes · {manifest}"
        )
        lines.append(
            f"| {entry.platform} | {entry.major_version} | `{entry.device}` | "
            f"{comparison} | {integrity} |"
        )
    lines.extend(
        [
            "",
            "## Integrity model",
            "",
            "Every entry is created only after a fresh destination commit matches its frozen",
            "source subtree's Git tree ID, file count, logical byte total, modes, README",
            "metadata, and generated manifest. Catalog links are pinned to immutable commits.",
            "",
            "The catalog tool never selects a diff, infers platform semantics from a path,",
            "pushes, merges, deletes legacy data, or rewrites a verified payload.",
            "",
            "## Frozen migration census",
            "",
            "`census` inventories the legacy repository from one full commit, not its",
            "worktree. The reviewed [source layout policy](migration/source-layout.json)",
            "names every payload root and every intentional exclusion. The command rejects",
            "missing or overlapping policy paths and any tracked file classified zero or",
            "multiple times, then records Git object IDs, file counts, logical bytes, modes,",
            "README metadata, and explicit blocker reasons in the generated",
            "[census](migration/census.json).",
            "",
            "Both known ordinary README labels (`## Inputs` and `## IPSWs`) must satisfy the",
            "same exact title and two-IPSW contract. A census row does not select a platform,",
            "device, destination shard, or migration route; those remain reviewed spec data.",
            "",
            "## Mechanical staging",
            "",
            "`stage` requires one reviewed spec, both local repository roots, and the full",
            "destination `HEAD` commit. It refuses dirty or pre-existing targets, reconstructs",
            "the source tree twice, and leaves only the payload and manifest staged for review.",
            "Run `validate-staged` again after inspection. Neither command commits or pushes.",
            "",
            "## Read-only discovery",
            "",
            "`discover` reads one explicitly supported iOS 27 or macOS 27 track policy,",
            "proves its baseline is the terminal merged manifest build, queries AppleDB with",
            "the exact policy selector, and emits canonical `current` or `candidate` JSON.",
            "It does not download firmware, modify a repository, schedule work, generate a",
            "diff, or publish anything.",
            "",
            "## Tooling",
            "",
            "```console",
            "uv sync --locked --all-groups",
            "uv run ipsw-diff-catalog --help",
            "uv run ipsw-diff-catalog stage --help",
            "uv run ipsw-diff-catalog validate-staged --help",
            "uv run ipsw-diff-catalog census --help",
            "uv run ipsw-diff-catalog discover --help",
            "uv run pytest",
            "uv run ruff format --check .",
            "uv run ruff check .",
            "uv run ty check src tests",
            "uv run ipsw-diff-catalog render --check",
            "uv run ipsw-diff-catalog audit",
            "uv run ipsw-diff-catalog census \\",
            "  --policy migration/source-layout.json \\",
            "  --source-repo /path/to/ipsw-diffs \\",
            "  --output migration/census.json \\",
            "  --check",
            "```",
            "",
            "[AUTOMATION.md](AUTOMATION.md) defines the separately gated migration,",
            "shard-generation, catalog-publication, and X-announcement transitions.",
            "",
        ]
    )
    return "\n".join(lines)


def _write_or_check(path: Path, content: str, *, check: bool) -> None:
    if check:
        try:
            observed = path.read_text(encoding="utf-8")
        except OSError as error:
            raise CatalogError(f"cannot check generated file {path}: {error}") from error
        if observed != content:
            raise CatalogError(f"generated file is stale: {path}")
        return
    path.write_text(content, encoding="utf-8")


def render(entries_dir: Path, readme: Path, catalog: Path, *, check: bool) -> None:
    entries = load_entries(entries_dir)
    _write_or_check(readme, render_readme(entries), check=check)
    _write_or_check(catalog, canonical_json(catalog_object(entries)), check=check)
